# Generated by Django 4.2.7 on 2023-11-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chatType",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("GROUP", "Group")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="FaceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=10
                    ),
                ),
                ("age", models.CharField(max_length=256)),
                ("leftEyeColor", models.CharField(max_length=256)),
                ("rightEyeColor", models.CharField(max_length=256)),
                ("hairColor", models.CharField(max_length=256)),
                ("skinColor", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                ("email", models.CharField(max_length=512)),
                ("chats", models.ManyToManyField(blank=True, to="app.chat")),
                (
                    "faceInfo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.faceinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.user",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.chat",
                    ),
                ),
            ],
        ),
    ]
